### ISSUE TITLE
about m6A validation set 

### ISSUE THREAD

**Issue by xieyy46** [weir12/DENA#13]
Hi DENA team! I' d want to know how you get the 4685 miCLIP sites identified in Nanopore direct RNA sequencing maps the complexity of Arabidopsis mRNA processing and m6A modification, while I found that the number of miCLIP sites identified in Nanopore direct RNA sequencing maps the complexity of Arabidopsis mRNA processing and m6A modification was 93046.
![image](https://user-images.githubusercontent.com/76148123/169948319-a82926aa-02a4-464d-9565-6688e622c080.png)

**Comment by weir12** [comment]
Hi,
I am sorry for the late reply due to the covid-19 pandemic.
The miCLIP data for both the original sites (93046) and the filtered sites (4685) were obtained by email contact with the corresponding author of `Gao Y, Liu X, Wu B, Wang H, Xi F, Kohnen MV, Reddy ASN, Gu L. Quantitative profiling of N6-methyladenosine at single-base resolution in stem-differentiating xylem of Populus trichocarpa using Nanopore direct RNA sequencing. Genome Biol. 2021 Jan 7;22(1):22. doi: 10.1186/s13059-020-02241-7. PMID: 33413586; PMCID: PMC7791831.`  

If you would like to get the original miclip data or the data processing strategy, please contact the author **Gu L** or **Gao Y**.

This is the email we used to use (availability unconfirmed now).
[lfgu@fafu.edu.cn](mailto:lfgu@fafu.edu.cn)
