### ISSUE TITLE
The scope of application of the DENA

### ISSUE THREAD

**Issue by zzf77** [weir12/DENA#18]
Hi developer,
Thank you for your tools, it's very nice. I have finished running my programs on human tissues, but I have a question. 
Could DENA be used to analyze human tissues?
Thanks!

Best wishes,
zhang zaifeng

**Comment by weir12** [comment]
Hi,
Our software tool has been specifically designed to detect m6A modifications and has been validated under specific experimental conditions. However, it is important to note that there may be biological variation between human samples, which may impact the tool's detection performance. Therefore, we strongly recommend performing comprehensive validation and evaluation of the tool before applying it to human samples, in order to understand its performance across a variety of contexts.

It is also important to note that we do not guarantee the tool's performance in all cases or contexts, and that the user assumes full responsibility for its use. Our team will not be held liable for any errors, discrepancies or unintended consequences arising from the use of this tool. As such, we recommend consulting with a qualified expert and/or performing additional validation experiments prior to making any conclusive claims or decisions based on the results obtained with this tool.

Best wishes
